Repository odpf/meteor, pull requests merged in 2021-09, with the labels that each got.

#198 docs: update installation and command usage
  README.md
  cmd/info.go
  docs/guides/0_Installation.md
  docs/guides/1_List_Plugins.md
  docs/guides/2_manage_recipes.md
  docs/guides/3_run_recipes.md
  docs/guides/4_deployment.md
  docs/guides/Introduction.md
  docs/guides/installation.md
  docs/guides/usage.md
  docs/reference/commands.md
Labels: documentation

#224 feat: improve command printing
  .goreleaser.yml
  README.md
  cmd/gen.go
  cmd/info.go
  cmd/lint.go
  cmd/list.go
  cmd/root.go
  cmd/run.go
  docs/assets/.DS_Store
  docs/assets/overview_4.svg
  go.mod
  go.sum
  plugins/extractors/bigquery/bigquery.go
  plugins/extractors/bigtable/bigtable.go
  plugins/extractors/cassandra/cassandra.go
  plugins/extractors/clickhouse/clickhouse.go
  plugins/extractors/csv/csv.go
  plugins/extractors/date/date.go
  plugins/extractors/elastic/elastic.go
  plugins/extractors/gcs/gcs.go
  plugins/extractors/github/github.go
  plugins/extractors/grafana/grafana.go
  plugins/extractors/kafka/kafka.go
  plugins/extractors/metabase/metabase.go
  plugins/extractors/mongodb/mongodb.go
  plugins/extractors/mssql/mssql.go
  plugins/extractors/mysql/mysql.go
  plugins/processors/enrich/processor.go
  plugins/sinks/columbus/sink.go
  registry/extractors.go
  registry/processors.go
  registry/sinks.go
Labels: enhancement

#221 fix: validate recipe name and plugin in gen
  cmd/gen.go
  generator/recipe.go
  generator/recipe.yaml
Labels: bug

#236 fix: missing import for populate
  plugins/extractors/clickhouse/README.md
  plugins/extractors/populate.go
Labels: bug

#237 fix: missing enrich metadata lead to error in sinking
  agent/agent.go
  models/metadata.go
  models/record.go
  plugins/extractors/bigquery/bigquery.go
  plugins/extractors/date/README.md
  plugins/extractors/date/date.go
  plugins/extractors/populate.go
  plugins/processors/enrich/processor.go
  plugins/sinks/columbus/sink.go
  plugins/sinks/columbus/sink_test.go
  utils/custom_properties.go
Labels: bug
