Repository odpf/meteor, pull requests merged in 2021-10, with the labels that each got.

#244 feat: use go-template pipeline to handle indentation in recipe generated
  generator/recipe.go
  generator/recipe.yaml
  plugins/extractors/bigquery/bigquery.go
  plugins/extractors/bigtable/bigtable.go
  plugins/extractors/cassandra/cassandra.go
  plugins/extractors/clickhouse/clickhouse.go
  plugins/extractors/couchdb/couchdb.go
  plugins/extractors/csv/csv.go
  plugins/extractors/elastic/elastic.go
  plugins/extractors/gcs/gcs.go
  plugins/extractors/github/github.go
  plugins/extractors/grafana/grafana.go
  plugins/extractors/kafka/kafka.go
  plugins/extractors/metabase/metabase.go
  plugins/extractors/mongodb/mongodb.go
  plugins/extractors/mssql/mssql.go
  plugins/extractors/mysql/mysql.go
  plugins/extractors/postgres/postgres.go
Labels: enhancement, core

#245 feat(agent): add retry mechanism
  agent/agent.go
  agent/agent_test.go
  agent/config.go
  agent/retrier.go
  cmd/lint.go
  cmd/root.go
  cmd/run.go
  config/config.go
  go.mod
  main.go
  plugins/errors.go
  plugins/sinks/columbus/sink.go
  plugins/sinks/columbus/sink_test.go
Labels: core

#238 feat: improve error handling
  agent/agent.go
  agent/batch.go
  agent/run.go
  agent/stream.go
  generator/recipe.go
  go.mod
  main.go
  metrics/statsd.go
  models/metadata.go
  models/record.go
  plugins/external/plugin.go
  plugins/extractors/bigquery/bigquery.go
  plugins/extractors/cassandra/cassandra.go
  plugins/extractors/clickhouse/clickhouse.go
  plugins/extractors/elastic/elastic.go
  plugins/extractors/gcs/gcs.go
  plugins/extractors/github/github.go
  plugins/extractors/grafana/grafana.go
  plugins/extractors/kafka/kafka.go
  plugins/extractors/metabase/metabase.go
  plugins/extractors/mongodb/mongodb.go
  plugins/extractors/mssql/mssql.go
  plugins/extractors/mysql/mysql.go
  plugins/extractors/postgres/postgres.go
  plugins/extractors/superset/superset.go
  plugins/extractors/superset/superset_test.go
  utils/config.go
  utils/custom_properties.go
Labels: enhancement
