Repository odpf/meteor, pull requests merged in 2022-01, with the labels that each got.

#291 fix: inconsistent test on agent module
  agent/agent.go
  agent/agent_test.go
  agent/config.go
Labels: bug

#293 fix: upgrade optimus extractor rpc to use v1beta1 APIs
  go.mod
  go.sum
  plugins/extractors/optimus/client.go
  plugins/extractors/optimus/optimus.go
  plugins/extractors/optimus/optimus_test.go
Labels: bug

#290 feat: connect database with connection URL
  plugins/extractors/bigquery/bigquery.go
  plugins/extractors/bigtable/bigtable.go
  plugins/extractors/cassandra/cassandra.go
  plugins/extractors/clickhouse/README.md
  plugins/extractors/clickhouse/clickhouse.go
  plugins/extractors/clickhouse/clickhouse_test.go
  plugins/extractors/couchdb/README.md
  plugins/extractors/couchdb/couchdb.go
  plugins/extractors/couchdb/couchdb_test.go
  plugins/extractors/csv/csv.go
  plugins/extractors/gcs/gcs.go
  plugins/extractors/github/github.go
  plugins/extractors/grafana/grafana.go
  plugins/extractors/kafka/kafka.go
  plugins/extractors/metabase/metabase.go
  plugins/extractors/mongodb/README.md
  plugins/extractors/mongodb/mongodb.go
  plugins/extractors/mongodb/mongodb_test.go
  plugins/extractors/mssql/README.md
  plugins/extractors/mssql/mssql.go
  plugins/extractors/mssql/mssql_test.go
  plugins/extractors/mysql/README.md
  plugins/extractors/mysql/mysql.go
  plugins/extractors/mysql/mysql_test.go
  plugins/extractors/optimus/optimus.go
  plugins/extractors/postgres/README.md
  plugins/extractors/postgres/postgres.go
  plugins/extractors/postgres/postgres_test.go
  plugins/extractors/superset/superset.go
Labels: enhancement

#298 fix(postgres): missing import of pq driver
  plugins/extractors/postgres/postgres.go
Labels: bug

#294 feat: add oracle extractor
  docs/docs/reference/extractors.md
  plugins/extractors/oracle/README.md
  plugins/extractors/oracle/oracle.go
  plugins/extractors/oracle/oracle_test.go
  plugins/extractors/populate.go
Labels: enhancement, extractor

#234 feat: add MariaDB extractor
  docs/docs/reference/extractors.md
  plugins/extractors/mariadb/README.md
  plugins/extractors/mariadb/mariadb.go
  plugins/extractors/mariadb/mariadb_test.go
  plugins/extractors/populate.go
Labels: extractor

#304 fix(config): error when running without config file
  config/config.go
Labels: bug
